// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/charsheet-layouts/CardMasonry.tsx": () => import("../components/mockups/charsheet-layouts/CardMasonry.tsx"),
  "./components/mockups/charsheet-layouts/DashboardHud.tsx": () => import("../components/mockups/charsheet-layouts/DashboardHud.tsx"),
  "./components/mockups/charsheet-layouts/TabbedRefinedA.tsx": () => import("../components/mockups/charsheet-layouts/TabbedRefinedA.tsx"),
  "./components/mockups/charsheet-layouts/TabbedRefinedB.tsx": () => import("../components/mockups/charsheet-layouts/TabbedRefinedB.tsx"),
  "./components/mockups/charsheet-layouts/TabbedSections.tsx": () => import("../components/mockups/charsheet-layouts/TabbedSections.tsx")
};
